echo Algorithm;Size;Run;Time;Result > results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll linkedList 10 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collection 10 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll linkedListbatch 10 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collectionbatch 10 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll recursiveCollection 10 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll linkedList 20 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collection 20 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll linkedListbatch 20 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collectionbatch 20 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll recursiveCollection 20 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll linkedList 100 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collection 100 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll linkedListbatch 100 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collectionbatch 100 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll recursiveCollection 100 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll linkedList 200 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collection 200 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll linkedListbatch 200 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collectionbatch 200 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll recursiveCollection 200 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll linkedList 1000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collection 1000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll linkedListbatch 1000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collectionbatch 1000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll recursiveCollection 1000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll linkedList 2000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collection 2000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll linkedListbatch 2000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collectionbatch 2000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll recursiveCollection 2000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll linkedList 50 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collection 50 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll linkedListbatch 50 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collectionbatch 50 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll recursiveCollection 50 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll linkedList 500 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collection 500 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll linkedListbatch 500 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collectionbatch 500 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll recursiveCollection 500 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll linkedList 5000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collection 5000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collectionbatch 5000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collection 10000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collectionbatch 10000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collection 20000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collectionbatch 20000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collection 50000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collectionbatch 50000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collection 100000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collectionbatch 100000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collection 200000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collectionbatch 200000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collection 500000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collectionbatch 500000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collection 1000000 >> results.csv
dotnet bin\Release\netcoreapp2.0\publish\ExtensibilityBenchmark.dll collectionbatch 1000000 >> results.csv